package com.janus.omega

object ModuleData {
    val categories: List<Pair<String, List<String>>> = listOf(
        "MOBILE OFFENSE" to listOf(
            "FRP_BYPASS", "BLOAT_MATRIX", "ROOT_DRAGNET", "BOOTLOOP_RESURRECTION",
            "GAME_ALCHEMIST", "APK_INJECTOR", "ADB_SHELL_MASTER", "USB_DEBUGGER",
            "IMEI_CHANGER", "BASEBAND_EXPLOIT", "BOOTLOADER_UNLOCK", "EDL_TRIGGER",
            "FASTBOOT_COMMANDER", "PARTITION_MAPPER", "DALVIK_DUMPER", "DEX_EXTRACTOR",
            "KEYSTORE_RIPPER", "PIN_BRUTEFORCE", "PATTERN_REVEALER", "FACE_BYPASS",
            "FINGERPRINT_SPOOF", "LOCKSCREEN_KILLER", "EMERGENCY_DIALER", "SAFE_MODE_FORCE",
            "FACTORY_RESET_BLOCKER", "OTA_INTERCEPTOR", "SAFETYNET_BYPASS", "PLAY_INTEGRITY_CRACK",
            "MAGISK_INSTALLER", "TWRP_FLASHER", "ZYGISK_MODULE", "LSP_FRAMEWORK",
            "KERNEL_PATCHER", "RAMDISK_EDITOR", "VBMETA_DISABLER", "DM_VERITY_KILLER"
        ),
        "FORENSICS" to listOf(
            "DATA_EXTRACTOR", "WAL_CARVER", "TIMELINE_RECON", "GEO_PROFILER",
            "DELETED_FILE_RECOVERY", "CACHE_ANALYZER", "SQLITE_DUMPER", "KEYLOGGER_SCAN",
            "ARTIFACT_COLLECTOR", "MEMORY_DUMP", "PROCESS_MONITOR", "NETWORK_HISTORY",
            "CALL_LOG_EXTRACT", "SMS_ARCHIVER", "CONTACT_HARVESTER", "MEDIA_CARVER",
            "CLOUD_TOKEN_RIPPER", "BROWSER_HISTORY", "APP_DATA_DUMP", "CRYPTO_WALLET_SCAN",
            "PASSWORD_VAULT_CRACK", "BIOMETRIC_CAPTURE", "SCREENSHOT_HARVEST", "LOCATION_HISTORY",
            "SENSOR_LOG_REPLAY", "ACCOUNT_TOKEN_DUMP", "OAUTH_INTERCEPTOR", "JWT_DECODER",
            "CERTIFICATE_EXTRACTOR", "BACKUP_DECRYPTOR", "AES_KEY_RECOVERY", "RSA_FACTORIZER"
        ),
        "NETWORK WARFARE" to listOf(
            "NMAP_CARTOGRAPHER", "WIFI_MARAUDER", "MITM_SSLSTRIP", "OSINT_ORACLE",
            "CELLULAR_SCANNER", "PACKET_INJECTOR", "DNS_POISONER", "ARP_SPOOFER",
            "BEACON_FLOODER", "DEAUTH_CANNON", "EVIL_TWIN_AP", "WPS_CRACKER",
            "HANDSHAKE_CAPTURE", "PMKID_ATTACK", "PROBE_LOGGER", "AIRCRACK_ENGINE",
            "HASHCAT_BRIDGE", "KRACK_EXPLOIT", "DRAGONBLOOD_ATTACK", "ROGUE_DHCP",
            "ICMP_REDIRECT", "VLAN_HOPPER", "MAC_FLOODER", "CDP_SPOOFER",
            "BGP_HIJACKER", "OSPF_POISONER", "TCP_RESET_INJECTOR", "SSL_BEAST",
            "HEARTBLEED_SCANNER", "SHELLSHOCK_PROBE", "LOG4J_EXPLOIT", "CSRF_FORGER"
        ),
        "CYBER WARFARE" to listOf(
            "QUANTUM_BRUTE", "SATELLITE_GRID_OVERRIDE", "BIOMETRIC_FORGE", "MESH_MARAUDER",
            "ZERO_DAY_SCANNER", "RANSOMWARE_DETECTOR", "KEYLOGGER_IMPLANT", "ROOTKIT_SCANNER",
            "POLYMORPHIC_SHELL", "ANTI_DEBUG", "CODE_CAVE_INJECTOR", "PROCESS_HOLLOWER",
            "DLL_HIJACKER", "REFLECTIVE_LOADER", "SHELLCODE_GEN", "EXPLOIT_FRAMEWORK",
            "PAYLOAD_ENCODER", "OBFUSCATION_ENGINE", "TRAFFIC_TUNNEL", "TOR_ROUTER",
            "I2P_BRIDGE", "DARKNET_PROXY", "C2_COMMANDER", "BOTNET_SPAWNER",
            "CREDENTIAL_STUFFING", "PASSWORD_SPRAY", "KERBEROAST", "PASS_THE_HASH",
            "GOLDEN_TICKET", "SILVER_TICKET", "DCsync_ATTACK", "LSASS_DUMPER"
        ),
        "SIGINT" to listOf(
            "RADIO_SCANNER", "GSM_INTERCEPTOR", "LTE_SNIFFER", "5G_MONITOR",
            "IMSI_CATCHER", "STINGRAY_DETECT", "SIGNAL_ANALYZER", "FREQ_MAPPER",
            "SDR_CONTROLLER", "RTL_SDR_BRIDGE", "HACKRF_INTERFACE", "AIRSPY_DRIVER",
            "FM_DECODER", "AM_DECODER", "SSB_DEMODULATOR", "APRS_DECODER",
            "AIS_TRACKER", "ACARS_MONITOR", "ADS_B_RECEIVER", "TRUNKING_FOLLOW",
            "P25_DECODER", "DMR_MONITOR", "D_STAR_DECODE", "TETRA_CRACK",
            "SATELLITE_PHONE_SCAN", "IRIDIUM_INTERCEPT", "THURAYA_MONITOR", "INMARSAT_DECODE",
            "GPS_SPOOFER", "GLONASS_JAM", "GALILEO_MONITOR", "BEIDOU_TRACK"
        ),
        "OSINT ORACLE" to listOf(
            "SOCIAL_MAPPER", "FACE_SEARCH", "USERNAME_HUNTER", "EMAIL_HARVESTER",
            "PHONE_LOOKUP", "IP_GEOLOCATOR", "DOMAIN_RECON", "WHOIS_DUMPER",
            "SHODAN_QUERY", "CENSYS_SCAN", "ZOOMEYE_SEARCH", "FOFA_PROBE",
            "DARK_WEB_SEARCH", "PASTEBIN_MONITOR", "BREACH_CHECK", "CREDENTIAL_DUMP",
            "LINKEDIN_SCRAPER", "TWITTER_INTEL", "INSTAGRAM_RECON", "FACEBOOK_OSINT",
            "TELEGRAM_SCAN", "DISCORD_HUNT", "GITHUB_RECON", "GITLAB_ENUM",
            "S3_BUCKET_FINDER", "AZURE_BLOB_SCAN", "GCP_STORAGE_ENUM", "DNS_BRUTEFORCE",
            "SUBDOMAIN_ENUM", "CERTIFICATE_TRANSPARENCY", "WAYBACK_MACHINE", "CACHE_SCRAPER"
        ),
        "HARDWARE GLITCH" to listOf(
            "VOLTAGE_INJECTOR", "CLOCK_GLITCHER", "USB_GLITCH_MK1", "JTAG_PROBE",
            "SWD_DEBUGGER", "UART_SNIFFER", "I2C_ANALYZER", "SPI_DUMPER",
            "EEPROM_READER", "FLASH_RIPPER", "BOOTROM_EXPLOIT", "ROM_PATCHER",
            "CHIP_DECAPPER", "FAULT_INJECTOR", "LASER_GLITCHER", "EMP_TRIGGER",
            "POWER_ANALYSIS", "EM_SIDE_CHANNEL", "TIMING_ATTACK", "CACHE_FLUSH",
            "ROWHAMMER", "SPECTRE_PROBE", "MELTDOWN_EXPLOIT", "PLATYPUS_ATTACK",
            "TPM_BYPASS", "SECURE_ENCLAVE_CRACK", "TRUSTZONE_EXPLOIT", "SGX_ATTACK",
            "COLD_BOOT", "DRAM_FREEZE", "BUS_PIRATE", "LOGIC_ANALYZER"
        ),
        "TITAN EXCLUSIVE" to listOf(
            "NEURAL_SYNC", "AR_HUD_THREAT", "CBRN_DETECTOR", "KINETIC_HARVESTER",
            "QUANTUM_ENCRYPT", "GHOST_NET_MESH", "FARADAY_CAGE_CTRL", "CHAMELEON_MODE",
            "BLACK_BOX_RECORDER", "VITAL_KILLSWITCH", "STETHOSCOPE_DIAG", "MJOLNIR_POWER",
            "SINGULARITY_AI", "TRANSCENDENCE_CORE", "HYDRA_RADIO", "HAILO8_ACCELERATE",
            "5G_MODEM_CTRL", "WIFI6E_SCANNER", "BT53_INTERCEPT", "NFC_EMULATOR",
            "BATTLESUIT_HUD", "THREAT_HIGHLIGHT", "BIOMETRIC_LOCK", "PANIC_WIPE",
            "DEAD_MAN_SWITCH", "DURESS_SIGNAL", "ENCRYPTED_COMMS", "QUANTUM_KEY_DIST",
            "POST_QUANTUM_SIGN", "LATTICE_CRYPTO", "KYBER_ENCRYPT", "DILITHIUM_SIGN"
        )
    )
}
