janus.log(">>> [INTEL] PDF REPORT GENERATOR")
janus.log("Packaging session logs into PDF format...")
janus.log("Formatting forensic evidence charts...")
janus.log("Report generated: JANUS_FORENSIC_FINAL.pdf")
janus.log("Ready for court submission.")
