janus.log(">>> [TITAN] HARDWARE GADGETS")
janus.log("[1] NFC Clone (PN532)")
janus.log("[2] Sub-GHz Replay (CC1101)")
janus.log("[3] IR Blast (LIRC)")
janus.log("[4] CAN Bus Unlock (OBD-II)")
janus.log("[5] UWB Tag Hunt")
janus.log("Activating Hardware Drivers...")
janus.shell("nfc-poll")
janus.shell("rtl_433 -f 433.92M -T 10")
janus.shell("cansend can0 123#DEADBEEF")
